### ISSUE TITLE
Will this work with my mammal of a room mate?

### ISSUE THREAD

**Issue by Jon-Biz** [levitanong/plotypus#2]
He just sits on the couch and lays rotten eggs until we have to leave the room.

**Comment by livtanong** [comment]
Yes it will! With Plotypus, he will be spending his time building charts and visualizing data, instead of stinking up the room!

**Comment by Jon-Biz** [comment]
![goodnewseveryone](https://cloud.githubusercontent.com/assets/1335043/8042190/59ba9dc8-0dd2-11e5-9d28-fba23e236207.png)
